### ISSUE TITLE
por via de regra, palavras nao traduzidas deveriam ser postas em italico?

### ISSUE THREAD

**Issue by cezaraugusto** [reactjs/pt-BR.reactjs.org#102]
no PR https://github.com/reactjs/pt-BR.reactjs.org/pull/72 houve um impasse em relacao a traducao do termo "hooks". Em geral pedimos para colocar em italico as palavras em ingles. Entretanto, palavras como "hooks", "state", "props" e outras sao do vocabulario do React, e em muitas revisoes feitas por mim eu ignorei o italico nelas.

nao tenho uma opiniao sobre se deveriamos colocar _todas_ as palavras em lingua inglesa/nao traduzidas em italico ou se deveria se basear em alguma regra. contando que isso seja documentado no glossario.

cc @reactjs/reactjs-org-portuguese-brazil-translation

**Comment by halian-vilela** [comment]
Então, como comentei lá na própria PR. Não acho necessário. 

Aplicar itálico nas palavras em inglês teria um impacto gigante no restante da tradução (além de uma necessidade de um "retro-review") já que tem uma lista crescente de termos que não devem ser traduzidos que foram definidos por consenso no Glossário.

Acho que pela natureza dessa documentação, pelo fato de ser um texto técnico, criar essa necessidade de colocar itálico nos termos em inglês é um preciosismo que não iria acrescentar muito na compreensão do texto.

Mas como disse, acho importante ouvir o @fjoshuajr pois talvez ele tenha enxergado algum motivo que não ficou claro para os demais.

Abraços!

**Comment by fjoshuajr** [comment]
Fiz um comentário sobre isso [aqui](https://github.com/reactjs/pt-BR.reactjs.org/pull/72#issuecomment-464550011).

A minha sugestão seria:
* Não usar itálico com o vocabulário do React (props, hooks), mas aqui temos que delimitar o que faz ou não parte desse vocabulário. Ex. render e state?

* Não/usar itálico se a palavra inglesa estiver entre parenteses. Acho que uma das discussões passadas foi acerca de: estado (_state_) ou estado (state).

* Usar se a expressão inglesa tiver tradução ambígua. ex: _event listener_

cc: @reactjs/reactjs-org-portuguese-brazil-translation

**Comment by eduardomoroni** [comment]
Eu sempre penso que não deveriamos bloquear um Merge por questoes como estas. Mergea e abre uma issue para discutir.
Eu creio que se a gente colocar muitas regras, fica dificil (confuso) para o pessoal contribuir. E na verdade isto nem fará tanta diferença no resultado final.
Ou poem italico em tudo, ou não poem. Por questoes de simplicidade.

**Comment by fjoshuajr** [comment]
Concordo com você @eduardomoroni, muitas regras acabam atrapalhando o processo. E debate de formatação é como espaços vs tabs 😅

@cezaraugusto como vocês usaram o itálico na tradução do You-Dont-Know-JS?

**Comment by halian-vilela** [comment]
> Fiz um comentário sobre isso [aqui](https://github.com/reactjs/pt-BR.reactjs.org/pull/72#issuecomment-464550011).
> 
> A minha sugestão seria:
> 
> * Não usar itálico com o vocabulário do React (props, hooks), mas aqui temos que delimitar o que faz ou não parte desse vocabulário. Ex. render e state?
> * Não usar itálico se a palavra inglesa estiver entre parenteses. Acho que uma das discussões passadas foi acerca de: estado (_state_) ou estado (state).
> * Usar se a expressão inglesa tiver tradução ambígua. ex: _event listener_
> 
> cc: @reactjs/reactjs-org-portuguese-brazil-translation

@fjoshuajr 

Concordo no geral, mas não entendi exatamente a última sugestão, pode dar um contexto? 

Pq se for o que entendi, acho que ela fica redundante com questão dos parênteses, que de toda forma já é o que temos sugerido: se o termo em inglês tiver uma tradução "pouco óbvia" a gente já coloca o termo original entre parênteses e sem o itálico para facilitar a compreensão.

Resumindo, eu concordo com o @eduardomoroni de que temos que simplificar. Pensando assim, não usar itálico é o melhor caso, hehehe... 😄 

**cc:** @reactjs/reactjs-org-portuguese-brazil-translation

**Comment by gmsecrieru** [comment]
👍  para simplificar o processo das PRs e abrir issues como follow-up para termos do glossário ou ajustes estéticos. Se pensarmos que a tradução como um todo é um projeto de longo prazo e que envolve manutenção por tempo indeterminado, esse tipo de detalhe pode ser facilmente observado (e eventualmente corrigido) por futuros leitores da documentação.

**Comment by fjoshuajr** [comment]
@halian-vilela no último exemplo falo do caso event-listener = escutador de eventos vs ouvinte de eventos, que é 'dificil' traduzir.

Concordo com @gmsecrieru:
> Se pensarmos que a tradução como um todo é um projeto de longo prazo e que envolve manutenção por tempo indeterminado, esse tipo de detalhe pode ser facilmente observado (e eventualmente corrigido) por futuros leitores da documentação.

**Comment by halian-vilela** [comment]
@cezaraugusto @fjoshuajr @eduardomoroni 

Pessoal, acho que essa questão já está resolvida né? Podemos fechar a issue?

Abraços!

**Comment by fjoshuajr** [comment]
👌
