### ISSUE TITLE
Problema ao clonar no Windows

### ISSUE THREAD

**Issue by lhcgoncalves** [reactjs/pt-BR.reactjs.org#111]
Aparentemente um dos pacotes depende da `libpng-dev`, que não está disponível no Win10.

Alguma sugestão de como contornar o problema sem trocar de OS?

**Comment by halian-vilela** [comment]
Oi @lhcgoncalves ! 

Parece que esse problema tem sido um problema relativamente comum. Eu não uso windows, mas dando uma pesquisada consegui achar algumas possíveis resoluções, pode testar?

1. [Editando o `resolutions` do seu `package`](https://discourse.roots.io/t/error-running-yarn-pngquant-failed-to-build-windows-10/13575)
2. [Compilando nativamente com Rust](https://pngquant.org/install.html) <- _desça até a parte do Windows e siga as instruções_

Se der certo, nos avise!

Abraços!

**Comment by halian-vilela** [comment]
@lhcgoncalves 

E aí? Algum progresso? Conseguiu?

Podemos fechar essa issue?

Valeu!

**Comment by lhcgoncalves** [comment]
Não deu certo, estou tentando outras alternativas =/

Em sex, 22 de fev de 2019 às 13:18, Halian Vilela <notifications@github.com>
escreveu:
