### ISSUE TITLE
Brazilian Portuguese Translation Final Tasks!

### ISSUE THREAD

**Issue by tesseralis** [reactjs/pt-BR.reactjs.org#123]
Congratulations!

You all are almost done translating the React docs into Portuguese! There are couple more errands to do before we can mark the project as "completed"

* [x] Replace "reactjs.org" to "pt-br.reactjs.org" in the following places:
  * [x] package.json
  * [x] site-constants.js
  * [x] gatsby-config.js
  * [x] MarkdownPage (the link href in "Edit this page")
* [x] Change `html.js` to have the attribute `lang="pt-BR"`
* [ ] Go over each section in the site to:
  * [ ] Make sure there are no formatting errors (dangling markdown/html tags) or untranslated English
  * [ ] Make sure the sections and style are consistent.
* [x] Change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25). One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program) (#132)

We're almost there everyone!

**Comment by halian-vilela** [comment]
@tesseralis 

Hey Nat! Will this have any immediate effect on something?

I mean, should we wait to have at least all the core pages done to make this changes or could we do it now just to make sure it will be ready?

Thanks!

**Comment by tibuurcio** [comment]
Thank you for pointing our last steps @tesseralis! We're almost there indeed :tada: 

I've made some of the changes on #124. I've also signed up for the DocSearch key, will comment here when we get their response.

**Comment by glaucia86** [comment]
@tesseralis awesome. We have to say thank you for all the brazilian community help. It was insane. But we will see about the topics that you listed it and then finish this issue. :)

**Comment by tesseralis** [comment]
@halian-vilela hmm. I think I'd wait until a certain section (like "main concepts") is completed, and then go over all of it to see if the whole thing feels consistent.

**Comment by WendellAdriel** [comment]
These items listed by @tesseralis, can I help with any of these or is there someone already doing that?

**Comment by WendellAdriel** [comment]
That's awesome, sorry to be away guys, but I had some personal issues that took a lot of my free time

**Comment by glaucia86** [comment]
@WendellAdriel you can take it this one:

``` 
* Change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25). **Signed up. Waiting for DocSearch API Key** One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program)
```

**Comment by WendellAdriel** [comment]
Great @glaucia86, I'll do that then!!!
Has any of the other maintainers signed up already for DocSearch?

**Comment by tibuurcio** [comment]
Hi everyone. I've already signed for DocSeach. I'm awaiting for their response and will comment here. We will probably hear from them this week since I applied on the weekend. Cheers!

**Comment by tesseralis** [comment]
@tibuurcio awesome! I just got the email from the Spanish repo after around a week. Shouldn't take too long.

**Comment by michellocana** [comment]
I have a little hack i used to make suggestions in PR's, and this can be useful to spot untranslated/misspelled words:
```js
document.designMode === 'on' 
// focus on some text or scroll the and you will see autocorrect suggestions 
document.designMode === 'off'
```

**Comment by tibuurcio** [comment]
Got the email from DocSearch yesterday already! I'll update our code as soon as I can :)

**Comment by tesseralis** [comment]
@tibuurcio I'm sorting out issues with docsearch for spanish here: https://github.com/reactjs/es.reactjs.org/pull/184#issuecomment-467345047

it may be useful to you

**Comment by eduardomoroni** [comment]
> * [ ] Go over each section in the site to:
>    * [ ] Make sure there are no formatting errors (dangling markdown/html tags) or untranslated English
>    * [ ] Make sure the sections and style are consistent.

I'm pointing some items out on https://github.com/reactjs/pt-BR.reactjs.org/issues/134
I'll need some help on that as well :)

**Comment by glaucia86** [comment]
@eduardomoroni about the #134 I already did a code review about the Nav bar situation and I asked to the contributor to make some changes on it! So... he did it and I already approve the contribution #131. Try to see right now @eduardomoroni if everything it's correct right now! ;)

**Comment by eduardomoroni** [comment]
It seems everything all right. Should mark this as done?

**Comment by glaucia86** [comment]
> It seems everything all right. Should wemark this as done?

![bitmoji](https://render.bitstrips.com/v2/cpanel/43533bc8-de9f-4e89-9f7d-f9a64b6254c4-51d9afb6-b666-4b20-ac39-494c4b2f62a7-v1.png?transparent=1&palette=1&width=246)

Agree w/ u @eduardomoroni. Let's finish this translation! :)
