### ISSUE TITLE
Propor melhorias nas paginas já traduzidas

### ISSUE THREAD

**Issue by jhonmike** [reactjs/pt-BR.reactjs.org#133]
A duvida seria se já podemos ir abrindo PRs propondo melhorias nas paginas já traduzidas até o momento ou se devemos esperar a conclusão da issue: #123

Conversando no canal do slack, @halian-vilela sugeriu a criação de uma issue para discutirmos sobre o tema e também sugeriu a criação de uma label "ajuste"

**Comment by eduardomoroni** [comment]
Eu acho que é OK criar PRs propondo melhorias.

**Comment by glaucia86** [comment]
Essa issue é de acordo com a issue #134? Se sim, podemos fechar ela?

**Comment by jhonmike** [comment]
@glaucia86 acho q sim, vou fechar mesmo!
