### ISSUE TITLE
Inconsistencias na página em produção.

### ISSUE THREAD

**Issue by eduardomoroni** [reactjs/pt-BR.reactjs.org#134]
Em https://github.com/reactjs/pt-BR.reactjs.org/issues/123 foi trazido que precisamos dar uma olhada em como a página está em geral. Pensei em criar esse issue para ir enumerando as inconsistencias e em seguidas irmos criando os PRs para consertar.

Link da documentação em PT-BR: https://pt-br.reactjs.org

**Comment by eduardomoroni** [comment]
Home page:

Cabeçalho está com a palavra `Communi` 
![image](https://user-images.githubusercontent.com/823150/53576189-68f9f400-3b73-11e9-8774-5a6128ad354d.png)
Versão em ingles:
![image](https://user-images.githubusercontent.com/823150/53576245-88911c80-3b73-11e9-92fa-bf971ceabb49.png)

Footer contem algums itens em ingles:
![image](https://user-images.githubusercontent.com/823150/53576279-9d6db000-3b73-11e9-8378-0afaf5eaf5f7.png)

**Comment by eduardomoroni** [comment]
# https://pt-br.reactjs.org/docs/add-react-to-a-website.html
Side bar está em ingles:
![image](https://user-images.githubusercontent.com/823150/53576441-eb82b380-3b73-11e9-9b6e-ac56eeeac689.png)
Versao em espanhol:
![image](https://user-images.githubusercontent.com/823150/53576459-f3daee80-3b73-11e9-81e9-6d2921b3bc54.png)

**Comment by halian-vilela** [comment]
Boa iniciativa @eduardomoroni !

Navbar está sendo traduzida na PR #131 - acho que podemos fazer uma revisão relâmpago e já aprovar, isso já vai melhorar o Look'n'Feel geral da página. O que ficar faltando, a gente vai fazendo aos poucos em outras PR's o que acham?

O restante de fato temos que ir controlando.

**Comment by jhonmike** [comment]
@eduardomoroni e @halian-vilela fui fazer o ajuste do Menu e a tradução do Rodapé e notei que ele depende do arquivo que esta no PR #131  e docs/nav.yml, então para tentar facilitar fiz oq faltava neste PR: #135

**Comment by glaucia86** [comment]
> @eduardomoroni e @halian-vilela feito os ajustes do menu do topo e rodapé no PR: #135

@jhonmike dá uma olhada lá no seu PR e faz os ajustes que coloquei lá. Assim que fizer, me sinalize que aprovarei direto o seu PR, okay! :)

**Comment by glaucia86** [comment]
> Boa iniciativa @eduardomoroni !
> 
> Navbar está sendo traduzida na PR #131 - acho que podemos fazer uma revisão relâmpago e já aprovar, isso já vai melhorar o Look'n'Feel geral da página. O que ficar faltando, a gente vai fazendo aos poucos em outras PR's o que acham?
> 
> O restante de fato temos que ir controlando.

Peço que deem uma olhada nesse PR. Fiz a review e tem alguns ajustes a serem feitos e algumas traduções q fiquei na dúvida como devem estar. ;)

**Comment by glaucia86** [comment]
@eduardomoroni vê se agora está okay a questão do navbar. Uma vez que já aprovamos a #131. Acredito que essa issue poderá ser fechada.

**Comment by jhonmike** [comment]
@glaucia86 o PR #131 é um conjunto com o PR #135 os dois já foram "mergeados". Acredito estar resolvido sim os itens citados acima :)

**Comment by eduardomoroni** [comment]
Alguns outros foram corrigidos aqui também https://github.com/reactjs/pt-BR.reactjs.org/pull/145
Vou dar mais uma olhada e ver como que ta as coisas :)

**Comment by eduardomoroni** [comment]
![image](https://user-images.githubusercontent.com/823150/53964023-bf74ae80-40ee-11e9-9b2b-83587fee1284.png)

**Comment by jhonmike** [comment]
opz, vou ajustar @eduardomoroni

**Comment by jhonmike** [comment]
PR esta aqui: https://github.com/reactjs/pt-BR.reactjs.org/pull/147 já tenho duas aprovações, esperando o +1 de algum manteiner.

**Comment by eduardomoroni** [comment]
Show de bola! Valeu galera
