### ISSUE TITLE
Suggestion: start versioning Glossary

### ISSUE THREAD

**Issue by gmsecrieru** [reactjs/pt-BR.reactjs.org#14]
I fear that #4 will eventually grow out of control and decisions/directions will be very hard to be tracked down in the long term.

We have been versioning these terms in [cezaraugusto/You-Dont-Know-JS](https://github.com/cezaraugusto/You-Dont-Know-JS/blob/portuguese-translation/WORDREFERENCE.md#jarg%C3%B5es-de-programa%C3%A7%C3%A3o) and IMO it has been a good thing since people can open issues/PRs proposing additions and the discussion is centralised on each particular change.

Thoughts?

**Comment by glaucia86** [comment]
I agree w/u 

cc: @cezaraugusto @fjoshuajr what do you think about it?

**Comment by klzns** [comment]
That would be helpful.

**Comment by cezaraugusto** [comment]
@gmsecrieru sounds good, could you create a PR for that?

**Comment by halian-vilela** [comment]
Hey guys, following @gmsecrieru suggestion, I made a simple `md` document in a dedicated repository with the current state of the glossary and some additions by myself.

Please fork it and we should keep discussing the best translation for recurring terms:
https://github.com/halian-vilela/pt-BR.reactjs.glossary

Feel free to suggest any improvements on format and relevant information.

**Comment by eduardomoroni** [comment]
Instead of having glossary outside this repo why don't just simply bring the glossary to here?

**Comment by fjoshuajr** [comment]
> Instead of having glossary outside this repo why don't just simply bring the glossary to here?

I agree. 
@halian-vilela can you create a PR for that? Something like `GLOSSARY.md` in the root folder.

**Comment by halian-vilela** [comment]
Hey guys, I made a separate repo cause I thought this should keep the same strutcture... but if that's ok, I'll bring it here right now.

**Comment by fjoshuajr** [comment]
The glossary is work in progress. 

Closing this.
