### ISSUE TITLE
Suggestion - Create a Discord Group about the Translation work

### ISSUE THREAD

**Issue by glaucia86** [reactjs/pt-BR.reactjs.org#15]
I was thinking in the possibility to create a group on Discord to discuss about the Translation.

What do you think about it?

**Comment by halian-vilela** [comment]
Totally agree discord is a great platform! I think github issues it not suitable for discussions with many opinions/references/suggestions about the same topic. Discord would be great for that.

**Comment by lamecksilva** [comment]
I agree

**Comment by eduardomoroni** [comment]
What do you think of creating a room on an existing channel? That way we can strengthen the community.
React's Doc refers to this channel (here)[https://discordapp.com/channels/102860784329052160/106239984767361024]
https://reactjs.org/tutorial/tutorial.html#help-im-stuck

I asked if there would be a problem creating a room there, then we could expand this idea to the others translation communities.

**Comment by eduardomoroni** [comment]
Update:
![image](https://user-images.githubusercontent.com/823150/52532502-9434b480-2d26-11e9-897b-0015f30abb9b.png)

O que voces acham de usar um canal existente de uma comunidade existente?

**Comment by glaucia86** [comment]
@eduardomoroni melhor ainda! Vamos abrir lá então! :)

**Comment by glaucia86** [comment]
> https://discordapp.com/channels/102860784329052160/106239984767361024

Pode criar o grupo lá e nos passar aqui @eduardomoroni ?

**Comment by halian-vilela** [comment]
> > https://discordapp.com/channels/102860784329052160/106239984767361024
> 
> Pode criar o grupo lá e nos passar aqui @eduardomoroni ?

Esse link tá vazio, é isso mesmo @glaucia86 ?

**Comment by glaucia86** [comment]
Não está não. Ou será que só é habilitado para quem está como Membro do React Community? Pode ser isso também @halian-vilela

**Comment by halian-vilela** [comment]
> Não está não. Ou será que só é habilitado para quem está como Membro do React Community? Pode ser isso também @halian-vilela

Pois é, qdo eu entro eu vejo isso:
![discord](https://user-images.githubusercontent.com/1423653/52578109-b142b380-2e0a-11e9-8d93-06159cc1accb.png)

**Comment by eduardomoroni** [comment]
Tentem usar este link:
https://discord.gg/Zn4bXAz

**Comment by glaucia86** [comment]
Obrigada @eduardomoroni. 
Pessoal, grupo criado no discord. Fechando a issue aqui
