### ISSUE TITLE
Inclusão de Novos Membros - React Community: Owner Blog Page

### ISSUE THREAD

**Issue by glaucia86** [reactjs/pt-BR.reactjs.org#150]
cc: @reactjs/reactjs-org-portuguese-brazil-translation 

Meninos, a página do blog, precisará de pessoas que estejam sempre traduzindo elas.
Nesse caso, 2 pessoas se mostraram super dispostas em manter essa página traduzida

* @lucianomlima 
* @Luanf 

Será que poderíamos incluir eles, como membros do React Community do pt-br?

O que vocês acham?

* [ ]  Blog **[NEEDS OWNER (SEVERAL) - LOWEST PRIORITY - NO PULL-REQUEST YET]**

**Comment by glaucia86** [comment]
Só uma ressalva: essa página do Blog precisará ser mantida constantemente. Ou seja, tem que colocar pessoas que de fato vão poder estar sempre traduzindo o blog. ;)

**Comment by lucianomlima** [comment]
👍

**Comment by eduardomoroni** [comment]
Vamo que vamo!

**Comment by Luanf** [comment]
Com prazer!

**Comment by jhonmike** [comment]
:clap: show

**Comment by jhonmike** [comment]
Pessoal já fiz a lista dos posts, acho q até o processo acima se concluir já podemos ir traduzindo algo hahaha

#151

**Comment by glaucia86** [comment]
Perfeito. Como foi aberto a issue #151 estarei fechando essa aqui. Obrigada a todos! :)
