### ISSUE TITLE
Community / Community Resources 

### ISSUE THREAD

**Issue by Duduzera1997** [reactjs/pt-BR.reactjs.org#153]
Percebi que as seguintes páginas:  "**Suporte/Cursos/Exemplos/Meetups/Conferencias/Artigos/Podcasts/Vídeos/Recursos Externos**" filhas de **Comunidade** ainda não estão traduzidas, o autor da issue #106 fez parte da tradução mas foi apenas em **Tools**. No entanto, posso ficar responsável por elas?

**Comment by eduardomoroni** [comment]
Acredito que sim. Manda bala.

Eu só não sei como que faço para conferir se não tem ninguém traduzindo
está parte. Mas pelo que eu lembro, ficou pra trás mesmo.

Em dom, 10 de mar de 2019 8:38 PM, Eduardo J. Nascimento <
notifications@github.com> escreveu:

**Comment by lucianomlima** [comment]
@Duduzera1997 faz um PR para cada página, assim simplifica a revisão com menos arquivos.

**Comment by Duduzera1997** [comment]
Certo, vou traduzi-las então.

Tranquilo @lucianomlima, farei conforme solicitado.
