### ISSUE TITLE
Translating '2016-07-13-mixins-considered-harmful.md'

### ISSUE THREAD

**Issue by igorjm** [reactjs/pt-BR.reactjs.org#238]
Issue #151

**Comment by jhonmike** [comment]
@igorjm não precisa criar uma issue, pode apenas subir o PR com a tradução, e qualquer dúvida comenta lá, olhe alguns PRs já fechado como modelo.

**Comment by igorjm** [comment]
@jhonmike entendi. Vou fechar essa então.
