### ISSUE TITLE
Correção na tradução de "perform a side-effect" na página React.Component

### ISSUE THREAD

**Issue by michellocana** [reactjs/pt-BR.reactjs.org#261]
Estava lendo a documentação da página React.Component, e vi que nessa linha (https://github.com/reactjs/pt-BR.reactjs.org/blame/master/content/docs/reference-react-component.md#L287) faltou ser traduzida a expressão "perform a side effect", acho que poderíamos ajustar para 
```
Se precisar **executar um side effect** (por exemplo, buscar dados ou uma animação)
```

**Comment by jhonmike** [comment]
@michellocana se puder abrir um PR com o ajuste agradeço, se não, assim que possível abrirei o PR

**Comment by michellocana** [comment]
posso sim, deixa comigo 😄

**Comment by jhonmike** [comment]
obrigado @michellocana !! vou fechar a issue pois o PR já esta na master!
