### ISSUE TITLE
Frase sem negação dando a entender sentido inverso

### ISSUE THREAD

**Issue by GabrielBibiano** [reactjs/pt-BR.reactjs.org#295]
Local: https://pt-br.reactjs.org/docs/dom-elements.html#suppresshydrationwarning

en: "React will not warn"

> If you set suppressHydrationWarning to true, React will not warn you about mismatches in the attributes and the content of that element.

pt-BR: "o React te avisará"

> Se você definir `suppressHydrationWarning` para `true`, o React te avisará sobre incompatibilidades nos atributos e no conteúdo daquele elemento.

**Comment by jcserracampos** [comment]
Solved!
