### ISSUE TITLE
Tradução da documentação para a v16.9.0

### ISSUE THREAD

**Issue by luizcieslak** [reactjs/pt-BR.reactjs.org#298]
Arquivos que precisam de alterações:

* [versions.yml](https://github.com/reactjs/pt-BR.reactjs.org/blob/master/content/versions.yml)

Novas páginas:

* [Profiler API](https://reactjs.org/docs/profiler.html) file: `reference-profiler.md` @luizcieslak 
* [React v16.9.0 and the Roadmap Update](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html) file: `2019-08-08-react-v16.9.0.md` @jhonmike 
* [Testing Environments](https://reactjs.org/docs/testing-environments.html) file: `testing-environments.md` @Chiiip
* [Testing Recipes](https://reactjs.org/docs/testing-recipes.html) file: `testing-recipes.md` @luizcieslak
* [Testing Overview](https://reactjs.org/docs/testing.html) file: `testing.md ` @lucianomlima

A ideia é ir editando a issue e relacionando as Issues.

cc: @reactjs/reactjs-org-portuguese-brazil-translation

**Comment by jhonmike** [comment]
Olá @luizcieslak show, acabei de ver a sincronização do bot da documentação original com a nova(pt-br) e vi que temos mais paginas que a `Profiler API`, vou criar uma issue com todas elas e vamos converter essa para a tradução do `Profiler API`, ae vc pode seguir com a tradução da mesma sem problemas. OK!

**Comment by jhonmike** [comment]
Seguinte o padrão sugerido pelo @jcserracampos  devemos criar uma issue para cada arquivo que formos traduzir!

**Comment by luizcieslak** [comment]
Combinado! Será que podemos usar a #277 para a pagina da Profiler API ou crio uma nova?

**Comment by luizcieslak** [comment]
Vou pegar a tradução de `Testing Recipes` #324

**Comment by jhonmike** [comment]
Boa @luizcieslak
