### ISSUE TITLE
Translate testing-environments.md

### ISSUE THREAD

**Issue by Chiiip** [reactjs/pt-BR.reactjs.org#319]
Vou começar a tradução do post [Testing Environments](https://reactjs.org/docs/testing-environments.html), que está listada aqui #298

**Comment by brunodahora** [comment]
Fala @Chiiip você conseguiu dar sequência nessa tradução? Precisa de ajuda?

**Comment by Chiiip** [comment]
Opa!

@brunodahora Então, eu já tenho uma tradução "pronta", mas que acho que requer uma revisada em alguns termos.  Acabei esquecendo de enviar para cá.

Eu fiquei em dúvida se deveria traduzir coisas como "rendering surface" e "test runner", já que eles não tinham uma tradução já definida no glossário. Na maioria dos casos, eu busquei outros blog posts que já tivessem sido traduzidos e tentei manter o padrão.

Você acha que eu devo fazer o PR agora para vocês avaliarem o que pode ser corrigido? Ou coloco em algum lugar antes?

**Comment by brunodahora** [comment]
@Chiiip vi que abriu o PR. Melhor coisa!

Vamos fazer um review e vamos discutindo por lá as traduções.
