### ISSUE TITLE
Link da página Glossário de Termos React na seção JSX

### ISSUE THREAD

**Issue by ricardoham** [reactjs/pt-BR.reactjs.org#366]
A página de Glósario na seção [JSX](https://pt-br.reactjs.org/docs/glossary.html#jsx), os links para redirencionar para as paginas:
I**ntroduzindo JSX** e **JSX in Depth**

Consta com os link fora da marcação de hyperlink, conforme a imagem:
![glosario-jsx](https://user-images.githubusercontent.com/16308040/68726815-6a543b00-05a1-11ea-8ddc-868d2c4ef99b.png)

**Comment by ricardoham** [comment]
Gostaria de saber se é possível eu contribuir para a correção? Caso se houver necessidade de um fix.

**Comment by jhonmike** [comment]
claro @ricardoham vc pode criar um PR com as correções e obrigado por reportar o erro, se não conseguir abrir o PR avisa aqui, que abrimos o PR com os ajustes!

**Comment by ricardoham** [comment]
fechando a issue, fix realizado em: [371](https://github.com/reactjs/pt-BR.reactjs.org/pull/371)
