### ISSUE TITLE
Discussions in Portuguese

### ISSUE THREAD

**Issue by klzns** [reactjs/pt-BR.reactjs.org#38]
Am I the only one that find it weird to be speaking English with people that speaks Portuguese?

I propose that we discuss things in issues and PRs in Portuguese. That will makes things more easy to everyone to contribute.

English-speakers-only are welcome to have discussions in English in this repo, although I think that would be a rare case, maybe when the React team reaches out to us.

**Comment by halian-vilela** [comment]
Também acho um pouco estranho, mas tava seguindo o fluxo. Principalmente pq esse já era o segundo projeto de tradução que participo, e o outro tb era primordialmente em inglês. Mas também não vejo estrita necessidade. 

Talvez seja uma regra da comunidade que todos os repos relacionados tenham as discussões em inglês? Não sei.

**Comment by tibuurcio** [comment]
Também acredito que pelo menos pra discutir sobre como traduzir certas partes, seria melhor fazer em português 😄 

Olhando pra os repositórios de espanhol, chinês e japonês que o time do React criou para validar as traduções inicialmente, a maioria das discussões parece ser feita em inglês,  com exceção de alguns comentários em issues específicos.

Pensei na ideia de criar labels e colocar nos issues que fossem discutidos em português, mas pode acontecer do label acabar sendo colocado em muitos issues abertos.

**Comment by glaucia86** [comment]
Como membro e moderadora do time, estávamos conversando a respeito. Tanto que já em alguns PR's já estou fazendo reviews e comentários usando português.

Mas, sinalizarei aos demais membros aqui.

cc: @cezaraugusto @WendellAdriel @eduardomoroni @fjoshuajr

**Comment by eduardomoroni** [comment]
Eu me sinto meio esnobe falando ingles na comunidade brasileira, mas como é uma comunidade de tradução acho de boa. Mas preferiria que fosse tudo em pt-BR :)

**Comment by cezaraugusto** [comment]
acho que a escrita em Inglês aconteceu por conta da issue original e acabou transferindo para as outras, e o processo foi se desenrolando. a escrita em Português é mais acessível para todos então acho válido 👍

**Comment by glaucia86** [comment]
Então resolvido pessoal. Estaremos falando em português, blz.
Fechando a issue! 👍
