### ISSUE TITLE
Glossary and Style Guide

### ISSUE THREAD

**Issue by WendellAdriel** [reactjs/pt-BR.reactjs.org#4]
# Style Guide

* Leave code blocks untranslated. (It is usually OK to translate comments inside them. **edit by @cezaraugusto**: also strings inside HTML/JSX can also pass but use your best judgement)
* Links to references (MDN, Wikipedia) should go to the Portuguese version.
* When referring to `React` itself, use `o React`.

# Common Translations

Suggestion on words and terms:

| Original word/term | Suggestion |
| ------------------ | ---------- |
| bug | erro |
| class | classe |
| context | contexto |
| controlled component | componente controlado |
| debugging | depuração|
| functional component | componente funcional |
| key | chave |
| library | biblioteca |
| lowercase | minúscula(s) |
| package | pacote |
| React element | Elemento React |
| React fragment | Fragmento React |
| render | renderizar (verb), renderizado (noun)
| uncontrolled component | componente não controlado |

# Content that doesn't need translation

* array
* arrow function
* bind
* bundle
* bundler
* camelCase
* callback
* DOM
* framework
* hook
* mock
* portal
* props
* ref
* state
* string
* template literal
* UI
* log

**Comment by eduardomoroni** [comment]
is `bind` one of them?

**Comment by WendellAdriel** [comment]
I think that `bind` needs to be translated, something link `vincular`, do you agree with that @eduardomoroni? we can put on the suggested list

**Comment by eduardomoroni** [comment]
If you take a look at this translation proposal https://github.com/reactjs/pt-BR.reactjs.org/pull/3, sometimes it makes sense to not translate `bind`, because you might be referencing the `bind` method.
But we translate `bound` and translate only the past tense, then the reading can be confusing for those who don't know what `bind` means.

I don't know what is the better way to approach honestly, but I think that making use of:

> os métodos de classe que não foram `bind` 

instead of 

> os métodos de classe que não foram vinculados

Can be friendlier for those with no knowledge of English and/or JS. Because people will understand that we're talking about the `bind` method.

**Comment by WendellAdriel** [comment]
I understood the issue. I finished reading the translation proposal now and yeah, it can be confusing. I think that `bind` can be a word that we won't translate.

We can also use **os métodos de classe que não foram feito `bind`.**

I'll add that to the glossary

**Comment by glaucia86** [comment]
> I think that `bind` needs to be translated, something link `vincular`, do you agree with that @eduardomoroni? we can put on the suggested list

Agree w/ @eduardomoroni many of video tutorials in portuguese teachs as 'bind'. I don't think unnecessary translate this word to portuguese.

**Comment by WendellAdriel** [comment]
I want your opinions on this one: the verb `log`, what do you think is the best option to translate this one? @glaucia86, @eduardomoroni?

**Comment by rafaelquintanilha** [comment]
> I want your opinions on this one: the verb `log`, what do you think is the best option to translate this one? @glaucia86, @eduardomoroni?

I don't think this has a good translation (mainly if you consider its etymology as a [reference to wooden logs](https://english.stackexchange.com/questions/335007/origin-of-log-to-log)). My suggestion is that we treat it as a substantive, like "adicionar ao log", "remover do log", etc.

**Comment by eduardomoroni** [comment]
I think we don't need to translate `log` as well, I remember the first time someone translated **Arcabouço** in a talk, It took me like 5min to understand that they were talking about a framework.
I someone doesn't understand log, they could easily google for it and figure out for themselves.

**Comment by WendellAdriel** [comment]
Yeah, I was thinking about that, but when we have something like "logs SOMETHING to the console". Which expression can I use to refer to that? I mean, what's the best option?

**Comment by rafaelquintanilha** [comment]
> Yeah, I was thinking about that, but when we have something like "logs SOMETHING to the console". Which expression can I use to refer to that? I mean, what's the best option?

I was thinking about that when I was trying to translate _print_. Feels really weird to say _imprimir_ even if the translation is pretty accurate. Maybe we can unify both cases and say _imprimir no console_ (the least bad translation I can think of).

**Comment by WendellAdriel** [comment]
Yeah, I was thinking about two options:

* escrever no console
* imprimir no console

**Comment by fjoshuajr** [comment]
I'm of the opinion that we should use 'imprimir no console'.

And what about markup? As in 'render components to static markup'.
I was thinking: 'renderizar componentes para markup estático'

**Comment by fjoshuajr** [comment]
'siblings' as well. 
e.g. 'Keys used within arrays should be unique among their siblings'

Possible options:
- 'elementos irmãos'
or
- 'items irmãos'

**Comment by cezaraugusto** [comment]
words that are also method names such as "bind", "call", "apply" should be translated along the original inside parenthesis such as `... conectar (bind)` or similar.

hard to tell without context but as PRs start to come using these terms we can refine the glossary

**Comment by cezaraugusto** [comment]
also applies for "state" for example i.e. "mudança de estado (state)". it's important to educate non-English readers about the word meaning without losing context

**Comment by fjoshuajr** [comment]
> words that are also method names such as "bind", "call", "apply" should be translated along the original inside parenthesis such as `... conectar (bind)` or similar.

Yeah, I liked this idea.

**Comment by glaucia86** [comment]
> > I want your opinions on this one: the verb `log`, what do you think is the best option to translate this one? @glaucia86, @eduardomoroni?
> 
> I don't think this has a good translation (mainly if you consider its etymology as a [reference to wooden logs](https://english.stackexchange.com/questions/335007/origin-of-log-to-log)). My suggestion is that we treat it as a noun, like "adicionar ao log", "remover do log", etc.

Agree! Do not need a translation to `log` word

**Comment by glaucia86** [comment]
I'll include `log` as a word unnecessary to translate

**Comment by cezaraugusto** [comment]
not sure if it was mentioned somewhere but we should consider not translating code blocks (comments allowed). I'm better if we do not but don't have a strong opinion. what do you all think?

**Comment by WendellAdriel** [comment]
It's the first item on the issue @cezaraugusto!!! :wink:

**Comment by cezaraugusto** [comment]
lol thanks @WendellAdriel

**Comment by WendellAdriel** [comment]
So, when translating something that relates to the `React` word, we need to define here a standard and stick to it, should we use:

* React
* a React
* o React

After defined, we need to include that on the Style Guide above.

cc: @glaucia86 @cezaraugusto @fjoshuajr

**Comment by cezaraugusto** [comment]
"o React" sounds good

**Comment by fjoshuajr** [comment]
> So, when translating something that relates to the `React` word, we need to define here a standard and stick to it, should we use:
> 
> * React
> * a React
> * o React
> 
> After defined, we need to include that on the Style Guide above.
> 
> cc: @glaucia86 @cezaraugusto @fjoshuajr

* o React

**Comment by WendellAdriel** [comment]
Great, I'll push this to the Style Guide and also fix my own translations, LOL!!! 🤣🤣🤣

**Comment by thadeu** [comment]
Effect as well?

**Comment by WeslleyNasRocha** [comment]
@thadeu im using effects and side effects

**Comment by WendellAdriel** [comment]
I don't see any cases that we can't translate effect, I think that's a common word

**Comment by WeslleyNasRocha** [comment]
@WendellAdriel something like this
>The Effect Hook lets you perform side effects in function components


>O Hook de efeito permite você realizar efeitos laterais em componentes funcionais

**Comment by rafaelquintanilha** [comment]
If you consider that "side effects" come from the concept of idempotence (idempotência), I guess "efeitos colaterais" is applicable.

**Comment by WeslleyNasRocha** [comment]
Huum, I thought that because its a common word like state and such

**Comment by ukita** [comment]
How we can translate `single-page apps`?

**Comment by fjoshuajr** [comment]
> How can we translate `single-page apps`?

I think this can't be translated because it's a proper noun and also has the acronym SPA.

**Comment by rafaelquintanilha** [comment]
What do you guys think about `mock`? I'd say this is a technical term and we shouldn't translate it, but if we do, the closest I can think of would be _imitação_.

**Comment by WendellAdriel** [comment]
I think that's better to not translate `mock`

**Comment by mrcelo** [comment]
Does `toolchain` fit into the do-not-translate category? Or is the translation `cadeia de ferramentas` commonly used enough to merit a case?

**Comment by negreirosleo** [comment]
Theres any translation sugested for `build`? like in `build steps`, I should use `etapas de build` or `etapas de construção?`

**Comment by gustavoaz7** [comment]
What about ```tags```? I would say to leave this in english

**Comment by mrcelo** [comment]
> Theres any translation sugested for `build`? like in `build steps`, I should use `etapas de build` or `etapas de construção?`

I'd say the usage of `build` among PT-BR devs has become ubiquitous enough to not need translation

**Comment by negreirosleo** [comment]
lifecycle should be translated?

**Comment by klzns** [comment]
I think the term "function components" should be translated as "componentes função" or "componentes de função", since it's different from "functional components".

**Comment by abnersajr** [comment]
We have these two terms for components too:

- stateless components: _componentes sem estado
- stateful components componentes com estado

**Comment by abnersajr** [comment]
> I think that's better to not translate `mock`, I'll add it to the list

Can add `spy` on the list too.

**Comment by lucasdeassis** [comment]
are we supposed to translate `default`?

I'm trying to think of a good fit for it but neither `padrão` or `pré-definido` do seem right.

**Comment by klzns** [comment]
Also it's important to notice that the term was changed from "functional component" to "function component", see here:
https://github.com/reactjs/reactjs.org/pull/863

**Comment by klzns** [comment]
> are we supposed to translate `default`?
> 
> I'm trying to think of a good fit for it but neither `padrão` or `predefinido` do seem right.

I would keep as `default`.

**Comment by negreirosleo** [comment]
@WendellAdriel could you please add `build` to non-translated words?

**Comment by fjoshuajr** [comment]
What about `stream` guys?
e.g. The stream returned from this method will return a byte stream encoded in utf-8.

**Comment by negreirosleo** [comment]
> What about `stream` guys?
> e.g. The stream returned from this method will return a byte stream encoded in utf-8.

I would go for `Este método retona uma bytestream codificada em utf-8`

**Comment by gmsecrieru** [comment]
Stream is a very common term in computing and holds a lot of meaning which might easily get lost during translation. 

I would say that this should not be translated, my 2 cents 💰

**Comment by negreirosleo** [comment]
At `React  pools events`, what do you think would be a good translation for that?

**Comment by ifdiego** [comment]
I'm not sure how to translate `Composing Components`?

**Comment by negreirosleo** [comment]
> I'm not sure how to translate `Composing Components`?

Could you give us a little more context?

**Comment by ifdiego** [comment]
> > I'm not sure how to translate `Composing Components`?
> 
> Could you give us a little more context?

It's this section in Components and Props: https://reactjs.org/docs/components-and-props.html#composing-components

It's about using the same component but with differente props.

**Comment by abnersajr** [comment]
Probably you can translate as "Compondo Componentes" or "Componentes
Compostos". It may depend on the context.

>

**Comment by glaucia86** [comment]
> Theres any translation sugested for `build`? like in `build steps`, I should use `etapas de build` or `etapas de construção?`

For me: `Etapas de Build`

**Comment by steniowagner** [comment]
props or propriedades?

e.g:

To modify a child, you re-render it with new props.

Para modificar um componente filho, você terá que re-renderizá-lo com as novas **props**.

Should I use props ou propriedades?

**Comment by klzns** [comment]
> props or propriedades?
> 
> e.g:
> 
> To modify a child, you re-render it with new props.
> 
> Para modificar um componente filho, você terá que re-renderizá-lo com as novas **props**.
> 
> Should I use props ou propriedades?

I would stick with `props` since the full term (`properties`) is never used in English.

**Comment by klzns** [comment]
> Probably you can translate as "Compondo Componentes" or "Componentes Compostos". It may depend on the context.
> […](#)

I agree with "Compondo Componentes"

**Comment by abnersajr** [comment]
> > Theres any translation sugested for `build`? like in `build steps`, I should use `etapas de build` or `etapas de construção?`
> 
> For me: `Etapas de Build`


I think `Etapas do Build` also is a valid translation depending on the context. Because steps are a process and these steps are towards to the Process.

**Comment by renato-bohler** [comment]
What is the best way to translate this?

>  React components can be defined by subclassing React.Component or React.PureComponent.

I'm currently thinking on

> Componentes React podem ser definidos ao extender `React.Component` ou `React.PureComponent`.

**Comment by renato-bohler** [comment]
And how about "wrapped"?

> React components can also be defined as functions which can be wrapped

> Componentes React também podem ser definidos como funções que podem ser envoltas

**Comment by abnersajr** [comment]
I'm translating the `CodeEditor` file but we have the following scenario:
`consider adding reactjs.org to the whitelist so the live code examples will work.`
In my opinion `live code` is another therm that we shouldn't translate.

**Comment by klzns** [comment]
> What is the best way to translate "subclassing"?
> 
> > React components can be defined by subclassing React.Component or React.PureComponent.
> 
> I'm currently thinking on
> 
> > Componentes React podem ser definidos ao extender `React.Component` ou `React.PureComponent`.

It's written `estender`

**Comment by mrcelo** [comment]
> And how about "wrapped"?
> 
> > React components can also be defined as functions which can be wrapped
> 
> > Componentes React também podem ser definidos como funções que podem ser envoltas

Perhaps "embrulhadas"?

**Comment by renato-bohler** [comment]
> > What is the best way to translate "subclassing"?
> > > React components can be defined by subclassing React.Component or React.PureComponent.
> > 
> > 
> > I'm currently thinking on
> > > Componentes React podem ser definidos ao extender `React.Component` ou `React.PureComponent`.
> 
> It's written `estender`

Whoops :face_with_head_bandage:

**Comment by klzns** [comment]
Should we translate the term `lifecycle`?

Examples:
> Hooks let you organize side effects in a component by what pieces are related (such as adding and removing a subscription), rather than forcing a split based on lifecycle methods.

> We'll talk more about how this compares to class lifecycles in [Using the Effect Hook]

I don't think so.

**Comment by fjoshuajr** [comment]
Guys,
_Italics_ vs Plain text for non-Translatable words?

**Comment by renato-bohler** [comment]
Should we translate `high order component`? Don't think so...

**Comment by lamecksilva** [comment]
"codebase" = "base de código" or "código-base" ?

**Comment by mrcelo** [comment]
> "codebase" = "base de código" or "código-base" ?

+1 "código-base"

**Comment by lamecksilva** [comment]
"código-base" then

**Comment by halian-vilela** [comment]
> > > I'm not sure how to translate `Composing Components`?
> > 
> > 
> > Could you give us a little more context?
> 
> It's this section in Components and Props: https://reactjs.org/docs/components-and-props.html#composing-components
> 
> It's about using the same component but with different props.

I would go with "Compondo componentes" to keep coherence with the next section "Extraindo componentes"

**Comment by halian-vilela** [comment]
> Should we translate `high order component`? Don't think so...

We should check how classic authors of Functional Programming were translated. I did a quick check in Wikipedia for `Higher-order function` but there's no Portuguese translation albeit all the available translations of the article were pretty literal, the Spanish one being what could be the most accurate, something like "Função de ordem superior" --> "Componente de ordem superior".

But it's a bit boring I guess, too formal... hahaha

**Comment by fmoliveira** [comment]
Hey guys,
What about **Error Boundaries**? It's not listed above but I haven't seen anybody translating it in blog posts. Should we leave it in English or translate it anyway? What do you think? 🤔

**Comment by halian-vilela** [comment]
> Hey guys,
> What about **Error Boundaries**? It's not listed above but I haven't seen anybody translating it in blog posts. Should we leave it in English or translate it anyway? What do you think? 🤔

For the sake of searchability, I don't think this kind of terms that almost compound a noun should be translated. It will be easier in the future for a user willing to know how to use error boudaries to search for this name than for "Limites de Erro" or "Fronteiras de Erro".

I've just translated the page for "Error Decoder" but I think that's different for not being a "feature" per se, it's rather just a description of a behaviour. 

Makes sense?

**Comment by fmoliveira** [comment]
Makes total sense @halian-vilela ! Searchability is a great argument for that. 👍 

Thank you!

**Comment by thealexandrelara** [comment]
> 
> 
> Should we translate the term `lifecycle`?
> 
> Examples:
> 
> > Hooks let you organize side effects in a component by what pieces are related (such as adding and removing a subscription), rather than forcing a split based on lifecycle methods.
> 
> > We'll talk more about how this compares to class lifecycles in [Using the Effect Hook]
> 
> I don't think so.

I think that it should be translated to:
Lifecycle methods = Métodos do Ciclo de Vida
Class lifecycles = Ciclos de vida da classe

**Comment by eduardomoroni** [comment]
is `bug === erro === error`?

**Comment by halian-vilela** [comment]
> is `bug === erro === error`?

I think semantically yes, but the context where they are used are pretty different.

**bug**: something unpredicted, not obvious or easy to spot, generally in the source code of the main codebase or associated libraries which prevents the code from running as expected

**error**: the result of a bug, which can be seem by an error message or something similar

- - -

That's raises the doubt if **bug** shouldn't be considered as _"doesn't need translation"_.

What do you guys think?

**Comment by jancassio** [comment]
Guys, are you really translating _Context_ (the name of Context api) to _"Contexto"_?

Since _props_ is never translated to _"propiedades"_, I don't think it makes any sense to describe _Context_ API using the pt-BR word _"Contexto"_. It could confuse readers about what's _Context_ (the api) and _"Contexto"_ at all.

**Comment by taynancid** [comment]
hi people,
what do you think is the best translation for "opt-in feature"?

**Comment by klzns** [comment]
> "codebase" = "base de código" or "código-base" ?

I think that better translates to "base de código".

"Código-base" would be something like "base code"?

In context it even makes more sense:

> Vou procurar na minha base de código.

> Vou procurar no meu código-base.

**Comment by klzns** [comment]
> Guys, are you really translating _Context_ (the name of Context api) to _"Contexto"_?
> 
> Since _props_ is never translated to _"propiedades"_, I don't think it makes any sense to describe _Context_ API using the pt-BR word _"Contexto"_. It could confuse readers about what's _Context_ (the api) and _"Contexto"_ at all.

That's a good point. I would stick with Context.

**Comment by michellocana** [comment]
> hi people,
> what do you think is the best translation for "opt-in feature"?

it depends of the context, but maybe "funcionalidade opcional"?

**Comment by michellocana** [comment]
what about 
> [...] `ReactDOM.render()` does not modify the **container node**

should we use "nodo contêiner" or "elemento contêiner"?

**Comment by moiseshilario** [comment]
How do you guys would translate "userland" ?

**Comment by michellocana** [comment]
> How do you guys would translate "userland" ?

If the phrase below is the one you are translating, 
> In general we resist adding features that can be implemented in userland.

i would translate to something like "[...] que podem ser implementadas do lado do usuário"

**Comment by tibuurcio** [comment]
@michellocana This is entirely personal but I believe _userland_ could be translated as _comunidade_, at least in your example, since it usually refers to open-source packages written by the community. 
> In general we resist adding features that can be implemented in userland.

> [...] que podem ser implementadas pela comunidade.

**Comment by gmsecrieru** [comment]
Hey everybody! Thanks for all the contributions and suggestions.

Defining common translations in a single issue makes it harder to keep track in the long term and also to reach consistency throughout our content.

We are starting to version control our Glossary (see #46) so if you would like to ask for suggestions on how to translate a given term please open an Issue for it. This will help to focus the discussion for each term while also helping to keep track when/how each term was added to our Glossary since we can link each issue to its own Pull Request.

Thanks again!

**Comment by GCrispino** [comment]
Hi! Should/How should we translate: 
- Warning article titles
  - e.g "Refs Must Have Owner Warning" (I translated it as "Aviso de Refs Precisam Ter um Dono")
  - Another approach would be to leave them untranslated.
  - Or meet it halfway (something like "Aviso 'Refs Must Have Owner'"
- Hyperlinks for specific sections
  - e.g: #strings-refs-outside-the-render-method in [refs-must-have-owner](https://github.com/reactjs/pt-BR.reactjs.org/blob/master/content/warnings/refs-must-have-owner.md) (My approach was to leave it as is)
- Terms like `ref` (I left as is, too)
