### ISSUE TITLE
Revert internal link translations

### ISSUE THREAD

**Issue by cezaraugusto** [reactjs/pt-BR.reactjs.org#42]
Some PRs got accepted including internal link translations which we later decided not to translate.

By internal links, we are referring to these:
e.g.
## Overview (#overview)

That should be translated to
## Visão Geral (#overview)

External links (MDN, Wikipedia, etc.) should link to the Portuguese version, if available.

The task here is to go through [this list](https://github.com/reactjs/pt-BR.reactjs.org/pulls?q=is%3Apr+is%3Aclosed) and check what links have been translated and undo that.

Either a PR for each document or a PR bundle with all reverts are valid and up to the author what to choose

**Comment by fjoshuajr** [comment]
Ok, can you be more specific on your message about what links we are talking about here? Just to avoid confusion.

**Comment by victorsilent** [comment]
> Ok, can you be more specific on your message about what links we are talking about here? Just to avoid confusion.

For sure, some links has just a english name link this one:
`[state of the art algorithms](http://grfia.dlsi.ua.es/ml/algorithms/references/editsurvey_bille.pdf)`
but could be translated without problems I guess, what do you think?

**Comment by cezaraugusto** [comment]
yes the link names are fine to translate but not the URL they refer to. even if they're just anchors

**Comment by glaucia86** [comment]
> yes the link names are fine to translate but not the URL they refer to. even if they're just anchors

The links about the headers. For ex:

## Teste de header(#teste-de-header)

Should translate once to help the users to navigate through the documentation.

**Comment by glaucia86** [comment]
https://github.com/reactjs/reactjs.org-translation/blob/master/style-guide.md

**Comment by tibuurcio** [comment]
Maybe we should translate the style guide into our own guide to make sure everyone has easy access to it? In the meantime I submitted #58 which fixes 3 PR's I could find with links translated.

**Comment by glaucia86** [comment]
agree @tibuurcio. 

cc: guys what do you think about it?

**Comment by fjoshuajr** [comment]
Yes, we could merge the universal style guide with the glossary, so we can have one file with all the rules.

**Comment by fjoshuajr** [comment]
Fechando a issue à favor de #69.
