### ISSUE TITLE
Andamento da tradução

### ISSUE THREAD

**Issue by andrecampll** [reactjs/pt-BR.reactjs.org#475]
Possuo interesse em contribuir, mas não ficou muito claro na área de Projects se o projeto de tradução ainda está em andamento. Posso abrir um PR com as traduções pendentes dos dois PR's que ainda estão abertos?

Abraços!

**Comment by jhonmike** [comment]
E ai @andrecampll, no momento não temos traduções disponíveis, mas temos 2 PRs que parecem abandonados, seria o caso de vc comentar lá se os donos dos PRs não estão com tempo de concluir as traduções, vc pode dar pull da branch deles e finalizar elas sem problema!!

resumindo é só mandar mensagem!!

e caso vc ache algum erro na tradução na doc já existente vc pode sim submeter um PR de correção, fique a vontade e espero ter conseguido responder sua dúvida!

**Comment by andrecampll** [comment]
Valeu @jhonmike, esclareceu bastante!!

**Comment by eduardomoroni** [comment]
@andrecampll a equipe do React postou um blog post dizendo que eles vao trabalhar em um rewrite nas docs, a motivacao maior eh o fato de a maioria dos exemplos estarem usando class components. Acredito que em breve teremos que traduzir tudo denovo. Quando esse dia chegar, a gente provavelmente vai dividir as  paginas para pessoas traduzirem.

**Comment by andrecampll** [comment]
@eduardomoroni entendi! vou ficar atento e pode contar com a minha colaboração quando isso acontecer 🚀
