### ISSUE TITLE
Translation Error (useCallback) - PT-BR

### ISSUE THREAD

**Issue by bruno-ralmeida** [reactjs/pt-BR.reactjs.org#524]
There is an error of translation (pt-br) in the page "API Hooks (useCallback)".

The word "memorizada" is missing letter "R".

link: https://pt-br.reactjs.org/docs/hooks-reference.html#usecallback

error: useCallback retornará uma versão **memoizada** do callback.

correct useCallback retornará uma versão **memorizada** do callback.

**Comment by eduardomoroni** [comment]
Opa @bruno-ralmeida beleza? Obrigado por criar o issue.
Porém nesse caso a tradução está "correta", perceba que o original é memo**i**zed e não memo**ri**zed.

https://pt.stackoverflow.com/questions/175412/o-que-%C3%A9-memoiza%C3%A7%C3%A3o
https://en.wikipedia.org/wiki/Memoization

Nesse caso eu não tenho certeza absoluta que a palavra memoizada existe no português, mas traduzir termos técnicos é complicado. Mas eu creio que é importante salientar que não se trata de **memorização**.
