### ISSUE TITLE
Traduzir content/blog/2021-06-08-the-plan-for-react-18.md

### ISSUE THREAD

**Issue by jhonmike** [reactjs/pt-br.reactjs.org#529]
Novo post no blog do react que precisa ser traduzido

aceitamos contribuições :p

**Comment by mdapper** [comment]
Eu posso traduzir esse post

**Comment by jhonmike** [comment]
Claro, manda ver @mdapper!!

só colocar um comentário aqui que estamos com problemas no deploy do site pt-br, e estamos aguardando alguém da equipe oficial do React responder, pois, não temos acesso ao sistema de deploy :(
