### ISSUE TITLE
Como contribuir na tradução?

### ISSUE THREAD

**Issue by Wanderson77** [reactjs/pt-br.reactjs.org#620]
Como proceder neste projeto?

**Comment by jhonmike** [comment]
Boa @Wanderson77, eu estava um pouco inativo nas traduções, mas vou retornar agora, e logo lhe trago notícias de como você também pode contribuir!!

**Comment by joaooliveiradev** [comment]
Também estou disponível para ajudar na tradução, @jhonmike, me diga se tem algo que posso fazer para ajudar.

**Comment by joaooliveiradev** [comment]
Bom, por enquanto vou ajudar avaliando os PR's, bora!

**Comment by jhonmike** [comment]
Bom, obrigado pessoal!

estou no processo agora de sincronizar as atualizações com o site em inglês, mas esse final de semana eu termino ae vou abrir uma nova issue com tudo que precisa ser feito no site Beta e aviso aqui!

**Comment by jhonmike** [comment]
tudo sincronizado, pessoal da uma olhada na issue de tradução, vamos manter a comunicação por lá das proximas traduções
