### ISSUE TITLE
Realizando Code Review das Traduções ao vivo pelo Twitch.tv

### ISSUE THREAD

**Issue by glaucia86** [reactjs/pt-BR.reactjs.org#66]
Pessoal! Volte e meia eu procuro fazer lives no meu canal do twitch.tv.
E como ultimamente estou envolvida nesse projeto do Code Review, estou realizando ele de maneira online e disponível para que todos possam acompanhar o nosso trabalho.

Segue o link abaixo: https://www.twitch.tv/glaucia_lemos86

Agradecemos aos esforços feitos por todos da Comunidade Técnica Brasileira. 😍

**Comment by eduardomoroni** [comment]
@glaucia86 podemos fechar esse issue?
