### ISSUE TITLE
Tradução: Componente LayoutHeader

### ISSUE THREAD

**Issue by thealexandrelara** [reactjs/pt-BR.reactjs.org#67]
Olá pessoal,
Resolvi trazer alguns pontos pois acredito que sejam importantes a serem discutidos antes de prosseguir com a tradução do componente LayoutHeader.

1. Existem 4 links principais no Header: Docs, Tutorial, Community e Blog. O problema é que dependendo o termo que for utilizado na tradução, pode prejudicar a exibição, por exemplo, traduzir Docs para Documentação (acréscimo de 8 caracteres).
2. Seguindo este mesmo ponto, o placeholder da busca possui o termo "Search docs", como isso poderia ser traduzido de uma forma enxuta?

Para exemplificar estes pontos, seguem abaixo algumas imagens (simulando o tamanho de
 tela dos iPhones 6/7/8).

**Original:**

![header-original](https://user-images.githubusercontent.com/20469356/52539405-e98fb680-2d64-11e9-9399-8f949efbb3a4.png)
![header-original-search](https://user-images.githubusercontent.com/20469356/52539409-f0b6c480-2d64-11e9-9888-0d6e626248fc.png)

**Traduzido:**

![header-translated](https://user-images.githubusercontent.com/20469356/52539414-fad8c300-2d64-11e9-95c5-3bb2a7b123f9.png)

Note que existe uma barra de rolagem embaixo dos links. Será que os usuários reparariam nela e conseguiriam navegar de forma apropriada? Alguma sugestão?

**Comment by glaucia86** [comment]
@thealexandrelara vc tem o link em inglês? Só para dar uma olhada e ver o que os outros times de outros idiomas estão fazendo?

**Comment by glaucia86** [comment]
[DÚVIDA]

cc: @cezaraugusto @fjoshuajr @tibuurcio

**Comment by tibuurcio** [comment]
Fiz uma pesquisa rápida em outros repositórios de tradução. Espanhol e Japonês que foram os utilizados como teste inicialmente ainda não traduziram essa parte. Russo já traduziu.

Jogando no tradutor eles traduziram "Docs" para o termo literal, "Documentação", enquanto que o placeholder da busca eles traduziram para "Pesquisar", sendo que esse último fica bem menor em russo.

Referências [Header.js](https://github.com/reactjs/ru.reactjs.org/blob/master/src/components/LayoutHeader/Header.js) e [DocSearch.js](https://github.com/reactjs/ru.reactjs.org/blob/master/src/components/LayoutHeader/DocSearch.js)

**Comment by thealexandrelara** [comment]
> 
> 
> @thealexandrelara vc tem o link em inglês? Só para dar uma olhada e ver o que os outros times de outros idiomas estão fazendo?

Você diz o link para o caminho do repositório em inglês onde está esse componente? Seria este [aqui](https://github.com/reactjs/reactjs.org/tree/master/src/components/LayoutHeader).

**Comment by fjoshuajr** [comment]
@tibuurcio acho que é o preço a pagar pela tradução 😅
Mesmo a versão em ingles nao cabe muito bem. Acho que com menu de hamburguer ficaria legal.

De qualquer forma, como tem o fade nas laterais e o scroll acho que dá para entender que tem outros links.

**Comment by halian-vilela** [comment]
Eu acho Docs bem bom, pra falar a verdade. Eu acho que para um desenvolvedor, com o sem experiência, Doc é um termo bem óbvio para "Documentação".

Eu manteria.

**Comment by glaucia86** [comment]
Não acho problema colocar 'Docs' também não. Pode colocar.

**Comment by thealexandrelara** [comment]
Fechando a issue porque já foi concluída no PR #89 . Obrigado a todos pela participação
