### ISSUE TITLE
GitHub suggestion bug

### ISSUE THREAD

**Issue by halian-vilela** [reactjs/pt-BR.reactjs.org#79]
Galera, só pra compartilhar com vocês:

Pessoal que está revisando, perceberam que o suggestion do GitHub as vezes não está fazendo o highlight correto das diffs?

Estou revisando esse PR: https://github.com/reactjs/pt-BR.reactjs.org/pull/72/files

E se vc olharem, algumas linhas não aparecem a diff na sugestão. Veja a linha 64, por exemplo: https://github.com/reactjs/pt-BR.reactjs.org/pull/72/files#r255440979

Isso tá acontecendo com vocês também?

Sabem se tem algum lugar que podemos reportar o bug? Eu não achei nada de muito diferente nessas linhas que pudesse estar causando isso, o único padrão que parece emergir é que todas são relativamente longas (ficam com mais de 6 linhas na interface).

**Comment by glaucia86** [comment]
Já tentou enviar esse report para o GH via twitter? @halian-vilela

**Comment by halian-vilela** [comment]
> Já tentou enviar esse report para o GH via twitter? @halian-vilela

Ainda não! Mas é uma boa ideia. Vou enviar lá mais tarde! Valeu!

Mas chegou a acontecer com vocês?

**Comment by glaucia86** [comment]
@halian-vilela todavia não.

**Comment by eduardomoroni** [comment]
Nunca aconteceu comigo também. Podemos fechar este issue? @halian-vilela

**Comment by halian-vilela** [comment]
Pode fechar @eduardomoroni, ainda está rolando, mas de fato tenho que enviar lá pro pessoal do GH, vou ver se faço isso hj mais tarde...

Valeu!
